const runas = [
  {
    "nombre": "Fehu",
    "nombre_alternativo": ["Fé", "Faiu", "Feo"],
    "letra": "F",
    "subnombre": "Abundancia de dar y recibir",
    "imagen": "fehu.png",
    "significado": "Fehu es una antena que atrae y distribuye energía. Es la primera letra del alfabeto futharc y representa el fuego comunitario, la alegría que se comparte, la abundancia que se prodiga.",
    "detalle": "Fehu representa el dinero. Es la primera runa del octeto correspondiente al plano físico que nos recuerda la condición de la vida encarnada. Fehu es energía que circula.",
    "invertida": "Cuando Fehu sale invertida, indica que la persona está embarcada en una tarea inútil como querer aferrar el agua o la arena que corre entre los dedos. Energía desperdiciada, despilfarro, malgastar dinero o fuerza vital.",
    "postura_corporal": "De pie con los pies juntos, sentimos la verticalidad. Los brazos se elevan por el frente y se dirigen hacia el cielo y hacia adelante. Las palmas de las manos están enfrentadas y la cabeza un poco levantada.",
    "ritual": "Existe un ritual perteneciente a los pueblos originarios llamado la atadura de los años, que nos ayuda a comprender el mensaje de Fehu. Al concluir un ciclo, se apagan la totalidad de los hogares y se enciende un fuego nuevo."
  },
  {
    "nombre": "Uruz",
    "nombre_alternativo": ["Ur", "Urs"],
    "letra": "U",
    "subnombre": "Fuerza de la iniciación",
    "imagen": "uruz.png",
    "significado": "Uruz representa al uro o buey salvaje, animal de fuerza indomable. Indica fuerza y sabiduría. Apela a la reserva individual que nos habita, a ese fuego propio.",
    "detalle": "En las antiguas tribus vikingas la matanza del uro era parte de un ritual iniciático. Su aparición en una tirada sugiere recurrir a las potencias del instinto como motor de vida.",
    "invertida": "Uruz invertida es runa de sacrificio. Sacrificio no significa sometimiento, sino hacer sagrado, elevar una materia densa, ofrendarla para recibir una energía sutil. La sugerencia de la runa es aceptar lo inútil del sacrificio frente a la contundencia del destino.",
    "postura_corporal": "Abrimos los pies en el ancho de caderas. Bajamos el tronco y los brazos, dejando que la cabeza cuelgue en dirección al piso. En esta posición podemos avanzar, golpeando rítmicamente con los pies en la tierra.",
    "ritual": ""
  },
  {
    "nombre": "Thurisaz",
    "nombre_alternativo": ["Thorn"],
    "letra": "TH",
    "subnombre": "Fuerza de un gigante",
    "imagen": "thurisaz.png",
    "significado": "Thurisaz está representada por el gigante Thor. Identifica una acción potente, directa e irreflexiva. Es runa de curación desestructurante.",
    "detalle": "En las leyendas vikingas, Thor rompe con estructuras anteriores para dar lugar a lo nuevo. Cuando esta runa aparece, el pasaje de una situación a otra es violento, sorpresivo o directo.",
    "invertida": "Thurisaz invertida: Toda esa potencia se vuelve en contra, produce enojo por no actuar en el momento propicio. El significado oracular puede ser mirada interior o que toda acción conduce al debilitamiento de la situación.",
    "postura_corporal": "De pie con los pies juntos. Los brazos suben por adelante hasta quedar paralelos al suelo a la altura del estómago. Las palmas de las manos hacia abajo y los dedos mayores unidos.",
    "ritual": ""
  },
  {
    "nombre": "Ansuz",
    "nombre_alternativo": ["Ansuz", "As", "Ansur"],
    "letra": "A",
    "subnombre": "En un principio fue el verbo",
    "imagen": "ansuz.png",
    "significado": "Ansuz simboliza la voz, la palabra, la poesía. Abre el pórtico del futharc e introduce en los caminos del conocimiento de sí.",
    "detalle": "Ansuz comunica con los dioses arquetípicos que habitan dentro de uno. Comunica el pensamiento con el exterior y representa la autoridad paterna.",
    "invertida": "Cuando Ansuz sale invertida significa llamarse a silencio, o puede ser que la energía del dios Loqui circunde la situación y haya engaño.",
    "postura_corporal": "De pie con pies juntos. Los brazos se elevan por adelante hasta quedar a 45 grados del cuerpo. Palmas hacia arriba y la garganta abierta en conexión con las manos.",
    "ritual": ""
  },
  {
    "nombre": "Raidho",
    "nombre_alternativo": ["Rad"],
    "letra": "R",
    "subnombre": "El viaje hacia mi destino",
    "imagen": "raidho.png",
    "significado": "Significa viaje, un largo viaje en carro. Es encuentro y comunicación con los pares. Comunicación a través de la acción.",
    "detalle": "El diseño muestra que una patita de la R está dando un paso, en acción de avanzar. Raidho es: Hacia donde voy, mi destino u objetivo.",
    "invertida": "Cuando Raidho sale invertida, significa estancamiento, viajes bloqueados, obstáculos en la comunicación y la acción.",
    "postura_corporal": "De pie, una pierna adelante, como dando un paso. Brazos acompañan el movimiento.",
    "ritual": ""
  },
  {
    "nombre": "Kaunaz",
    "nombre_alternativo": ["Kenaz", "Kaunan"],
    "letra": "K",
    "subnombre": "El ojo de Dios",
    "imagen": "kaunaz.png",
    "significado": "Kaunaz es el ojo de Dios, el fuego del conocimiento, la chispa divina, la creatividad y la visión interna.",
    "detalle": "Representa la luz que nos permite ver en la oscuridad, la inspiración y la revelación.",
    "invertida": "Kaunaz invertida puede indicar confusión, pérdida de claridad, dificultad para ver la solución.",
    "postura_corporal": "De pie, el cuerpo ligeramente inclinado, brazos en forma de cuenco para simbolizar la apertura al fuego interior.",
    "ritual": ""
  },
  {
    "nombre": "Gebo",
    "nombre_alternativo": ["Gyfu"],
    "letra": "G",
    "subnombre": "El regalo de una pareja equilibrada",
    "imagen": "gebo.png",
    "significado": "Gebo representa el regalo, la pareja, el equilibrio entre dar y recibir. Es la runa de la generosidad y los vínculos.",
    "detalle": "Simboliza el encuentro de dos partes que se reconocen y logran fundirse en un instante infinito.",
    "invertida": "Gebo no tiene posición invertida, siempre es positiva.",
    "postura_corporal": "De pie, brazos abiertos simulando un intercambio o abrazo.",
    "ritual": ""
  },
  {
    "nombre": "Wunjo",
    "nombre_alternativo": ["Wunyo", "Wungo"],
    "letra": "W",
    "subnombre": "Un lugar de llegada para mi alegría",
    "imagen": "wunjo.png",
    "significado": "Wunjo representa la alegría, la meta alcanzada, el bienestar, la armonía y la felicidad compartida.",
    "detalle": "Simboliza el momento de celebración por los logros y la unión con los demás.",
    "invertida": "Wunjo invertida indica tristeza, rupturas, pérdida de alegría o disonancia en los vínculos.",
    "postura_corporal": "De pie, brazos en alto en señal de alegría o victoria.",
    "ritual": ""
  },
  {
    "nombre": "Hagalaz",
    "nombre_alternativo": ["Hagal"],
    "letra": "H",
    "subnombre": "El arma de los gigantes de la escarcha",
    "imagen": "hagalaz.png",
    "significado": "Hagalaz simboliza el granizo, las fuerzas destructivas que traen cambio y transformación inesperada.",
    "detalle": "Es la runa de la crisis, el quiebre necesario para un nuevo orden.",
    "invertida": "Hagalaz no tiene invertida, siempre es disruptiva.",
    "postura_corporal": "De pie, brazos cruzados sobre el pecho, representando protección ante la tormenta.",
    "ritual": ""
  },
  {
    "nombre": "Naudhiz",
    "nombre_alternativo": ["Nauthiz", "Naud"],
    "letra": "N",
    "subnombre": "La maestría que da el dolor",
    "imagen": "naudhiz.png",
    "significado": "Naudhiz es la necesidad, la carencia, el dolor que enseña y forja carácter, los retos inevitables.",
    "detalle": "Simboliza la maestría que da el sufrimiento y la posibilidad de transformación.",
    "invertida": "Naudhiz invertida: Resistirse al aprendizaje, negar el dolor, estancamiento.",
    "postura_corporal": "De pie, una mano sobre el corazón y otra sobre el vientre, reconociendo la necesidad.",
    "ritual": ""
  },
  {
    "nombre": "Isa",
    "nombre_alternativo": [],
    "letra": "I",
    "subnombre": "El hielo. El silencio del movimiento",
    "imagen": "isa.png",
    "significado": "Isa representa el hielo, la quietud, el estancamiento necesario para observar y reflexionar.",
    "detalle": "Es la pausa antes de la acción, el silencio que permite la transformación.",
    "invertida": "Isa no tiene invertida, su mensaje es siempre de quietud.",
    "postura_corporal": "De pie, cuerpo recto y relajado, brazos a los lados.",
    "ritual": ""
  },
  {
    "nombre": "Jera",
    "nombre_alternativo": [],
    "letra": "J",
    "subnombre": "La paciencia de sostener un ciclo",
    "imagen": "jera.png",
    "significado": "Jera es la cosecha, el ciclo, la recompensa tras el esfuerzo y la espera paciente.",
    "detalle": "Simboliza los frutos del trabajo y los procesos naturales de la vida.",
    "invertida": "Jera no tiene invertida, siempre es positiva en su ciclo.",
    "postura_corporal": "De pie, brazos formando un círculo frente al pecho.",
    "ritual": ""
  },
  {
    "nombre": "Eihwaz",
    "nombre_alternativo": ["Eiwaz", "Eihaz"],
    "letra": "EI",
    "subnombre": "Muerte y transformación en el corazón del futharc",
    "imagen": "eeihwaz.png",
    "significado": "Eihwaz representa el tejo, la transformación, la muerte necesaria para el renacimiento.",
    "detalle": "Simboliza el cambio interior profundo y la superación de obstáculos.",
    "invertida": "Eihwaz no tiene invertida, su mensaje es de transformación.",
    "postura_corporal": "De pie, brazos cruzados sobre la cabeza en forma de Y.",
    "ritual": ""
  },
  {
    "nombre": "Perdhro",
    "nombre_alternativo": ["Perdhro", "Perth"],
    "letra": "P",
    "subnombre": "El secreto se oculta en nuestro corazón",
    "imagen": "perdhro.png",
    "significado": "Perthro es el misterio, el destino, los secretos revelados por el tiempo y la experiencia.",
    "detalle": "Simboliza el azar, el juego y el poder oculto en cada persona.",
    "invertida": "Perthro invertida: Secretos dañinos, falta de claridad, manipulación.",
    "postura_corporal": "De pie, manos juntas frente al pecho como guardando un secreto.",
    "ritual": ""
  },
  {
    "nombre": "Algiz",
    "nombre_alternativo": ["Elhaz"],
    "letra": "Z",
    "subnombre": "La oportunidad de decir no",
    "imagen": "algiz.png",
    "significado": "Algiz es la protección, la defensa, la oportunidad de poner límites y decir no.",
    "detalle": "Simboliza el escudo energético y la conexión con lo divino.",
    "invertida": "Algiz invertida: Vulnerabilidad, falta de protección, peligro.",
    "postura_corporal": "De pie, brazos abiertos hacia arriba en forma de V.",
    "ritual": ""
  },
  {
    "nombre": "Sowilo",
    "nombre_alternativo": ["Sowilu", "Sowilo"],
    "letra": "S",
    "subnombre": "Un camino hacia el Sol",
    "imagen": "sowilo.png",
    "significado": "Sowilo es el sol, la victoria, la realización, la claridad y la energía vital.",
    "detalle": "Simboliza la luz que disipa la oscuridad y la fuerza para lograr metas.",
    "invertida": "Sowilo no tiene invertida, siempre es positiva.",
    "postura_corporal": "De pie, brazos extendidos hacia el sol, mirando hacia arriba.",
    "ritual": ""
  },
  {
    "nombre": "Tiwaz",
    "nombre_alternativo": ["Teiwaz", "Tyr"],
    "letra": "T",
    "subnombre": "Reposando en la fe",
    "imagen": "tiwaz.png",
    "significado": "Tiwaz es la runa del guerrero, el autosacrificio, la fe y la justicia.",
    "detalle": "Simboliza la victoria que se obtiene con honestidad y compromiso.",
    "invertida": "Tiwaz invertida: Injusticia, falta de fe, derrota.",
    "postura_corporal": "De pie, un brazo extendido hacia arriba, simbolizando la lanza.",
    "ritual": ""
  },
  {
    "nombre": "Berkano",
    "nombre_alternativo": ["Berkana", "Berkanan"],
    "letra": "B",
    "subnombre": "El coraje de lo femenino",
    "imagen": "berkano.png",
    "significado": "Berkano es la madre, el nacimiento, la fertilidad y el crecimiento.",
    "detalle": "Simboliza la protección, el cuidado y la renovación.",
    "invertida": "Berkano invertida: Estancamiento, problemas familiares, falta de crecimiento.",
    "postura_corporal": "De pie, brazos formando un óvalo sobre el vientre.",
    "ritual": ""
  },
  {
    "nombre": "Ehwo",
    "nombre_alternativo": ["Ehwo"],
    "letra": "E",
    "subnombre": "Un paseo que enlaza universos",
    "imagen": "ehwo.png",
    "significado": "Ehwaz es el caballo, la confianza, la cooperación y el movimiento equilibrado.",
    "detalle": "Simboliza la unión de fuerzas y el progreso en común.",
    "invertida": "Ehwaz invertida: Desconfianza, ruptura de sociedades, estancamiento.",
    "postura_corporal": "De pie, piernas abiertas y brazos moviéndose como si cabalgara.",
    "ritual": ""
  },
  {
    "nombre": "Mannaz",
    "nombre_alternativo": [],
    "letra": "M",
    "subnombre": "La raza humana",
    "imagen": "mannaz.png",
    "significado": "Mannaz es el ser humano, la conciencia social, el yo en relación al otro.",
    "detalle": "Simboliza la colaboración y la autosuperación.",
    "invertida": "Mannaz invertida: Soledad, alienación, dificultades sociales.",
    "postura_corporal": "De pie, brazos abiertos hacia los lados, simbolizando la humanidad.",
    "ritual": ""
  },
  {
    "nombre": "Laguz",
    "nombre_alternativo": [],
    "letra": "L",
    "subnombre": "Un cuerpo de agua",
    "imagen": "laguz.png",
    "significado": "Laguz es el agua, la intuición, la fluidez y la emocionalidad.",
    "detalle": "Simboliza la flexibilidad y la conexión con el inconsciente.",
    "invertida": "Laguz invertida: Caos emocional, confusión, falta de dirección.",
    "postura_corporal": "De pie, brazos en movimiento ondulante como imitando olas.",
    "ritual": ""
  },
  {
    "nombre": "Ingwaz",
    "nombre_alternativo": ["Inguz", "Ing"],
    "letra": "NG",
    "subnombre": "La potencia de un comienzo",
    "imagen": "ingwaz.png",
    "significado": "Ingwaz es la semilla, el potencial, la gestación de algo nuevo.",
    "detalle": "Simboliza la concentración de energía antes del nacimiento de un proyecto.",
    "invertida": "Ingwaz no tiene invertida.",
    "postura_corporal": "De pie, manos en forma de semilla frente al abdomen.",
    "ritual": ""
  },
  {
    "nombre": "Dagaz",
    "nombre_alternativo": [],
    "letra": "D",
    "subnombre": "La irrupción de la luz",
    "imagen": "dagaz.png",
    "significado": "Dagaz es el amanecer, el cambio radical, la iluminación y la apertura.",
    "detalle": "Simboliza la transformación total y los nuevos comienzos.",
    "invertida": "Dagaz no tiene invertida.",
    "postura_corporal": "De pie, brazos abiertos simulando recibir la luz del día.",
    "ritual": ""
  },
  {
    "nombre": "Othalaz",
    "nombre_alternativo": ["Othalaz", "Odal"],
    "letra": "O",
    "subnombre": "El liderazgo: un estado que viene de la acción de los ancestros",
    "imagen": "othalaz.png",
    "significado": "Othala es la herencia, el patrimonio, los ancestros y el hogar.",
    "detalle": "Simboliza la transmisión de valores y la protección del linaje.",
    "invertida": "Othala invertida: Pérdida de raíces, conflictos familiares, desapego.",
    "postura_corporal": "De pie, brazos formando un triángulo encima de la cabeza.",
    "ritual": ""
  }
];